FROM ruby:2.6.6

RUN apt-get update -yqq \
		&& apt-get install -yqq --no-install-recommends \
		postgresql-client vim nodejs openssl \
		&& rm -rf /var/lib/apt/lists

ENV APP_NAME toms_bass_lessons
ENV APP_PATH /usr/src/app
ENV PATH $APP_PATH/bin:$PATH
ENV BUNDLE_PATH /gems

WORKDIR $APP_PATH

ADD . $APP_PATH

ENV RAILS_ENV production

EXPOSE 4002
CMD ./lib/docker-entrypoint.sh