development: &default
  mode: sandbox
  client_id: <%= Rails.application.credentials.paypal[:client_id] %>
  client_secret: <%= Rails.application.credentials.paypal[:client_secret] %>

test:
  <<: *default

production:
  <<: *default
  mode: sandbox